# Generated by Django 4.0.4 on 2022-05-09 01:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
        ('job', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Apply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apply_date', models.DateTimeField(auto_now_add=True)),
                ('apply_cv', models.FileField(blank=True, null=True, upload_to='')),
                ('apply_applicant', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.applicantprofile')),
                ('apply_job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='job.job')),
            ],
        ),
    ]
