# Generated by Django 4.0.4 on 2022-05-08 10:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0008_remove_companyadditional_company_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Apply',
            fields=[
                ('apply_id', models.AutoField(primary_key=True, serialize=False)),
                ('apply_date', models.DateTimeField(auto_now_add=True)),
                ('apply_cv', models.FileField(blank=True, null=True, upload_to='')),
                ('apply_applicant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.applicantprofile')),
            ],
        ),
    ]
