# Generated by Django 4.0.4 on 2022-05-07 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apply', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='apply',
            name='apply_cv',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
