# Generated by Django 4.0.4 on 2022-05-11 04:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0004_rename_job_slug_job_slug'),
        ('apply', '0002_alter_apply_apply_job'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apply',
            name='apply_job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='job.job'),
        ),
    ]
