# Generated by Django 4.0.4 on 2022-05-12 10:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
        ('apply', '0005_alter_apply_apply_job'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apply',
            name='apply_applicant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.applicantprofile'),
        ),
    ]
