# Generated by Django 4.0.4 on 2022-05-07 06:31

import django.core.validators
from django.db import migrations, models
import django.db.models.expressions
import django.db.models.functions.text


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email')),
                ('phone_number', models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 10 digits allowed.", regex='^\\+?1?\\d{9,10}$')])),
                ('first_name', models.CharField(max_length=50, verbose_name='fname')),
                ('last_name', models.CharField(max_length=50, verbose_name='lname')),
                ('profile_image', models.ImageField(upload_to=None, verbose_name='imagfields')),
                ('user_type', models.CharField(choices=[('Company', 'Company'), ('Applicant', 'Applicant')], max_length=50, verbose_name='user_type')),
                ('date_of_birth', models.DateField(verbose_name='DOB')),
                ('is_active', models.BooleanField(default=True, verbose_name='is_active')),
                ('is_admin', models.BooleanField(default=False, verbose_name='is_admin')),
                ('is_staff', models.BooleanField(default=False)),
                ('join_date', models.DateTimeField(auto_now_add=True)),
                ('last_login', models.DateTimeField(auto_now_add=True)),
                ('is_superadmin', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddConstraint(
            model_name='profiles',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('first_name'), django.db.models.expressions.OrderBy(django.db.models.functions.text.Lower('last_name'), descending=True), name='first_last_name_unique'),
        ),
        migrations.CreateModel(
            name='Applicant',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('account.profiles',),
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('account.profiles',),
        ),
    ]
