# Generated by Django 4.0.4 on 2022-05-20 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profiles',
            name='profile_image',
            field=models.ImageField(upload_to='image/', verbose_name='imagfields'),
        ),
    ]
