# Generated by Django 4.0.4 on 2022-05-07 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Applicant',
        ),
        migrations.DeleteModel(
            name='Company',
        ),
        migrations.CreateModel(
            name='ApplicantProfile',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('account.profiles',),
        ),
        migrations.CreateModel(
            name='CompanyProfile',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('account.profiles',),
        ),
    ]
