# Generated by Django 4.0.4 on 2022-05-08 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_profiles_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profiles',
            name='user_type',
            field=models.CharField(blank=True, choices=[('Company', 'Company'), ('Applicant', 'Applicant')], default=[], max_length=50, null=True, verbose_name='user_type'),
        ),
    ]
