# Generated by Django 4.0.4 on 2022-05-08 02:13

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_profiles_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profiles',
            name='user_type',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Company', 'Company'), ('Applicant', 'Applicant')], default=[], max_length=17, null=True),
        ),
    ]
