# Generated by Django 4.0.4 on 2022-05-08 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_companyadditional_applicantadditional'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companyadditional',
            name='company_email',
        ),
    ]
