# Generated by Django 4.0.4 on 2022-05-08 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_remove_companyadditional_company_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companyadditional',
            name='company_logo',
        ),
    ]
