# Generated by Django 4.0.4 on 2022-05-10 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='job_slug',
            field=models.SlugField(default='senior-dajngo-developer'),
            preserve_default=False,
        ),
    ]
