# Generated by Django 4.0.4 on 2022-05-10 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0002_job_job_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='job_slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
