# Generated by Django 4.0.4 on 2022-05-20 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0005_alter_job_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='job_salary',
            field=models.CharField(max_length=220),
        ),
    ]
